main: my_first_plugin.App
name: Basic_commands
version: 0.1
commands:
   kit:
      description: Your description
      usage: /<command> <amountOfDiamonds>
      permission: yourplugin.yourcommandpermission