main: my_first_plugin.App
name: Basic_commands
version: 0.1
commands:
    kit:
      description: A simple command to give user diamonds and bricks
      usage: /<command> <amountOfDiamonds>
      permission: basiccmds.useKitsbasic
    gui:
      description: A simple command to test opening a gui from command
      usage: /<command>
      permission: basiccmds.useGuiTest
    playerinfo:
      description: A simple command that displays information about the current player or player that is sent
      usage: /<command> <player>
      permission: basiccmds.usePlayerInfo
    fly:
      description: A simple command that allows to enable or disable flight
      usage: /<command>
      permission: basiccmds.useFly