main: my_first_plugin.App
name: Basic_commands
version: 0.1
commands:
   kit:
      description: A simple command to give user diamonds and bricks
      usage: /<command> <amountOfDiamonds>
      permission: basiccmds.useKitsbasic